import type { ComponentRole } from "./component-roles.js";
import { websiteArchetypeIds, type WebsiteArchetypeId } from "./website-archetypes.js";

export type ComponentImplementationStatus = "planned" | "schema-ready" | "renderable";

export type ComponentDefinition = {
  id: string;
  label: string;
  role: ComponentRole;
  description: string;
  suitableFor: WebsiteArchetypeId[];
  requiredData: string[];
  optionalData: string[];
  variants: string[];
  defaultVariant: string;
  implementationStatus: ComponentImplementationStatus;
  qualityRules: string[];
  incompatibleWith?: string[];
};

type ComponentInput = Omit<ComponentDefinition, "defaultVariant" | "implementationStatus" | "qualityRules" | "requiredData" | "optionalData" | "suitableFor" | "variants"> & {
  suitableFor?: WebsiteArchetypeId[];
  requiredData?: string[];
  optionalData?: string[];
  variants?: string[];
  defaultVariant?: string;
  implementationStatus?: ComponentImplementationStatus;
  qualityRules?: string[];
};

const allWebsiteArchetypes: WebsiteArchetypeId[] = [...websiteArchetypeIds];

function component(input: ComponentInput): ComponentDefinition {
  const variants = input.variants?.length ? input.variants : ["default"];

  return {
    ...input,
    suitableFor: input.suitableFor ?? allWebsiteArchetypes,
    requiredData: input.requiredData ?? [],
    optionalData: input.optionalData ?? [],
    variants,
    defaultVariant: input.defaultVariant ?? variants[0] ?? "default",
    implementationStatus: input.implementationStatus ?? "planned",
    qualityRules: input.qualityRules ?? ["Use sourced business data and avoid unsupported claims."],
  };
}

const componentDefinitionList = [
  component({ id: "page-shell", label: "Page shell", role: "layout", description: "Top-level page wrapper for shared layout structure." }),
  component({ id: "header", label: "Header", role: "layout", description: "Default website header with navigation support.", implementationStatus: "schema-ready", variants: ["default", "centered", "with-cta"] }),
  component({ id: "header-transparent", label: "Transparent header", role: "layout", description: "Header variant intended for image-led hero layouts." }),
  component({ id: "header-centered", label: "Centered header", role: "layout", description: "Header variant with centered navigation and brand." }),
  component({ id: "header-with-cta", label: "Header with CTA", role: "layout", description: "Header variant with a prominent action button." }),
  component({ id: "mobile-navigation", label: "Mobile navigation", role: "navigation", description: "Responsive mobile navigation surface." }),
  component({ id: "footer", label: "Footer", role: "layout", description: "Default website footer.", implementationStatus: "schema-ready", variants: ["default", "minimal", "contact", "commerce"] }),
  component({ id: "footer-minimal", label: "Minimal footer", role: "layout", description: "Compact footer for simple websites and landing pages." }),
  component({ id: "footer-contact", label: "Contact footer", role: "layout", description: "Footer focused on contact details and local trust." }),
  component({ id: "footer-commerce", label: "Commerce footer", role: "commerce", description: "Footer for product or commerce websites." }),
  component({ id: "footer-legal", label: "Legal footer", role: "support", description: "Footer with legal, privacy and regulated-industry notes.", suitableFor: ["private-clinic", "micro-ecommerce"] }),
  component({ id: "section-container", label: "Section container", role: "layout", description: "Shared section width and spacing wrapper." }),
  component({ id: "grid-layout", label: "Grid layout", role: "layout", description: "Reusable grid layout primitive." }),
  component({ id: "split-layout", label: "Split layout", role: "layout", description: "Reusable two-column layout primitive." }),
  component({ id: "card-grid", label: "Card grid", role: "layout", description: "Reusable card grid primitive." }),
  component({ id: "masonry-grid", label: "Masonry grid", role: "layout", description: "Reusable masonry-style media grid primitive." }),
  component({ id: "tabs", label: "Tabs", role: "utility", description: "Tabbed content primitive." }),
  component({ id: "accordion", label: "Accordion", role: "utility", description: "Accordion content primitive." }),
  component({ id: "modal", label: "Modal", role: "utility", description: "Modal interaction primitive." }),
  component({ id: "drawer", label: "Drawer", role: "utility", description: "Drawer interaction primitive." }),
  component({ id: "sticky-bar", label: "Sticky bar", role: "conversion", description: "Sticky conversion or contact bar." }),
  component({ id: "breadcrumbs", label: "Breadcrumbs", role: "navigation", description: "Breadcrumb navigation component." }),

  component({ id: "hero-default", label: "Default hero", role: "hero", description: "Generic hero section for simple pages.", implementationStatus: "schema-ready", variants: ["centered", "split", "minimal"] }),
  component({ id: "hero-local", label: "Local hero", role: "hero", description: "Hero section for local businesses.", suitableFor: ["local-service", "cafe-bistro", "restaurant", "beauty-salon", "local-retail"], variants: ["centered", "map-focused", "photo-overlay"] }),
  component({ id: "hero-service", label: "Service hero", role: "hero", description: "Hero section for local service websites.", suitableFor: ["local-service"], requiredData: ["business.name", "business.category", "business.location"], optionalData: ["business.phone", "business.serviceArea", "business.rating", "business.heroImage"], variants: ["direct-response", "trust-card", "image-right", "emergency-focused", "minimal-local"], implementationStatus: "schema-ready", qualityRules: ["State the service, location and primary action clearly.", "Emergency or same-day claims require source data.", "Phone CTA should be used only when phone is known."] }),
  component({ id: "hero-craft", label: "Craft hero", role: "hero", description: "Hero section for artisan and custom-production websites.", suitableFor: ["tradesman-craft"], variants: ["editorial", "workshop-photo", "minimal-maker"] }),
  component({ id: "hero-local-gastro", label: "Local gastro hero", role: "hero", description: "Hero section for cafes, bistros, bakeries and local gastro businesses.", suitableFor: ["cafe-bistro", "restaurant"], requiredData: ["business.name", "business.category"], optionalData: ["business.address", "business.openingHours", "business.heroImage", "business.rating"], variants: ["warm-centered", "photo-left", "photo-overlay", "editorial-split", "map-focused"], implementationStatus: "schema-ready", qualityRules: ["Communicate what the place is and where it is.", "Do not invent opening hours, ratings, menu items or awards.", "Primary CTA should encourage visit, menu view or reservation depending on available data."] }),
  component({ id: "hero-restaurant", label: "Restaurant hero", role: "hero", description: "Hero section for restaurants, bars and dining concepts.", suitableFor: ["restaurant"], variants: ["reservation-first", "menu-first", "dark-photo", "chef-story"] }),
  component({ id: "hero-beauty", label: "Beauty hero", role: "hero", description: "Hero section for salons, barbers, tattoo studios and beauty services.", suitableFor: ["beauty-salon"], variants: ["soft", "premium", "before-after", "booking-first"] }),
  component({ id: "hero-fitness", label: "Fitness hero", role: "hero", description: "Hero section for fitness, yoga, pilates and sport studios.", suitableFor: ["fitness-studio"], variants: ["bold", "trial-first", "community", "trainer-led"] }),
  component({ id: "hero-personal-trust", label: "Personal trust hero", role: "hero", description: "Hero section for trust-heavy personal expert websites.", suitableFor: ["therapist-coach"], variants: ["calm-centered", "portrait-split", "method-led"] }),
  component({ id: "hero-clinic", label: "Clinic hero", role: "hero", description: "Hero section for private clinics and medical practices.", suitableFor: ["private-clinic"], variants: ["clinical-clean", "doctor-led", "booking-first"] }),
  component({ id: "hero-agent", label: "Real estate agent hero", role: "hero", description: "Hero section for real estate agent personal-brand websites.", suitableFor: ["real-estate-agent"], variants: ["portrait", "valuation-first", "luxury-dark"] }),
  component({ id: "project-hero", label: "Project hero", role: "hero", description: "Hero section for real estate project microsites.", suitableFor: ["real-estate-project"], variants: ["visualization", "location-first", "lead-first"] }),
  component({ id: "hero-accommodation", label: "Accommodation hero", role: "hero", description: "Hero section for accommodation and guest house websites.", suitableFor: ["accommodation"], variants: ["photo-full", "booking-first", "location-led"] }),
  component({ id: "hero-retail", label: "Retail hero", role: "hero", description: "Hero section for shops, showrooms and local retail.", suitableFor: ["local-retail"], variants: ["storefront", "featured-product", "offer-led"] }),
  component({ id: "hero-product-brand", label: "Product brand hero", role: "hero", description: "Hero section for product brands and micro e-commerce websites.", suitableFor: ["micro-ecommerce"], variants: ["product-photo", "brand-story", "collection-first"] }),
  component({ id: "hero-expert", label: "Expert hero", role: "hero", description: "Hero section for consultants and B2B experts.", suitableFor: ["consultant-expert"], variants: ["authority", "problem-first", "calendar-first"] }),
  component({ id: "hero-course", label: "Course hero", role: "hero", description: "Hero section for courses, workshops and education programs.", suitableFor: ["course-workshop"], variants: ["outcome-first", "instructor-led", "date-first"] }),
  component({ id: "hero-event", label: "Event hero", role: "hero", description: "Hero section for events, festivals and conference microsites.", suitableFor: ["event-microsite"], variants: ["date-venue", "performer-led", "ticket-first"] }),
  component({ id: "hero-portfolio", label: "Portfolio hero", role: "hero", description: "Hero section for creative portfolios.", suitableFor: ["creative-portfolio"], variants: ["minimal", "work-first", "editorial"] }),
  component({ id: "hero-mission", label: "Mission hero", role: "hero", description: "Hero section for nonprofit and community websites.", suitableFor: ["nonprofit-community"], variants: ["mission-first", "impact-first", "community-photo"] }),
  component({ id: "hero-saas", label: "SaaS / MVP hero", role: "hero", description: "Hero section for startup and MVP landing pages.", suitableFor: ["startup-mvp-landing"], variants: ["waitlist", "product-preview", "problem-first"] }),
  component({ id: "hero-hiring", label: "Hiring hero", role: "hero", description: "Hero section for employer and hiring microsites.", suitableFor: ["hiring-microsite"], variants: ["roles-first", "culture-first", "benefits-first"] }),
  component({ id: "hero-with-image", label: "Hero with image", role: "hero", description: "Generic image-led hero variant." }),
  component({ id: "hero-with-video", label: "Hero with video", role: "hero", description: "Generic video-led hero variant." }),
  component({ id: "hero-centered", label: "Centered hero", role: "hero", description: "Centered hero variant." }),
  component({ id: "hero-editorial", label: "Editorial hero", role: "hero", description: "Editorial-style hero variant." }),
  component({ id: "hero-dark-premium", label: "Dark premium hero", role: "hero", description: "Dark premium hero variant." }),
  component({ id: "hero-warm-local", label: "Warm local hero", role: "hero", description: "Warm hero variant for local businesses." }),

  component({ id: "navigation-menu", label: "Navigation menu", role: "navigation", description: "Primary navigation menu." }),
  component({ id: "anchor-navigation", label: "Anchor navigation", role: "navigation", description: "In-page anchor navigation." }),
  component({ id: "page-intro", label: "Page intro", role: "story", description: "Introductory content section for a page." }),
  component({ id: "section-intro", label: "Section intro", role: "story", description: "Reusable section heading and intro block.", implementationStatus: "schema-ready" }),
  component({ id: "info-strip", label: "Info strip", role: "utility", description: "Compact information strip for key facts." }),
  component({ id: "contact-strip", label: "Contact strip", role: "conversion", description: "Compact strip with phone, email, address or booking action.", implementationStatus: "schema-ready" }),
  component({ id: "date-venue-strip", label: "Date and venue strip", role: "event", description: "Event date and venue facts.", suitableFor: ["event-microsite"], implementationStatus: "schema-ready" }),
  component({ id: "opening-status-badge", label: "Opening status badge", role: "local", description: "Badge showing current or general opening status." }),
  component({ id: "language-switcher", label: "Language switcher", role: "navigation", description: "Locale switcher for multilingual websites." }),
  component({ id: "back-to-top", label: "Back to top", role: "utility", description: "Back-to-top utility action." }),

  component({ id: "services-grid", label: "Services grid", role: "offer", description: "Grid of service cards for local businesses and service providers.", suitableFor: ["local-service", "beauty-salon", "therapist-coach", "consultant-expert", "private-clinic"], requiredData: ["services"], optionalData: ["serviceDescriptions", "serviceIcons", "pricesFrom"], variants: ["icon-cards", "numbered-list", "category-tabs", "pricing-cards", "split-detail"], implementationStatus: "schema-ready", qualityRules: ["Services must come from source data or be clearly generic placeholders.", "Prices must not be invented.", "Each card should have a concrete label and short benefit-oriented description."] }),
  component({ id: "services-cards", label: "Services cards", role: "offer", description: "Service cards with concise descriptions.", suitableFor: ["therapist-coach", "consultant-expert", "private-clinic"] }),
  component({ id: "services-list", label: "Services list", role: "offer", description: "Simple service list." }),
  component({ id: "service-detail-cards", label: "Service detail cards", role: "offer", description: "Detailed service cards." }),
  component({ id: "service-category-tabs", label: "Service category tabs", role: "offer", description: "Tabbed service categories." }),
  component({ id: "service-area-map", label: "Service area map", role: "local", description: "Service coverage area map or list.", suitableFor: ["local-service"], implementationStatus: "schema-ready" }),
  component({ id: "pricing-from", label: "Pricing from", role: "offer", description: "Starting-price teaser when source prices exist.", qualityRules: ["Never invent prices."] }),
  component({ id: "pricing-table", label: "Pricing table", role: "offer", description: "Pricing table for packages or plans." }),
  component({ id: "pricing-plans", label: "Pricing plans", role: "offer", description: "Course, membership or service pricing plans.", suitableFor: ["course-workshop", "startup-mvp-landing"] }),
  component({ id: "pricing-teaser", label: "Pricing teaser", role: "offer", description: "Early pricing teaser for MVP or product pages.", suitableFor: ["startup-mvp-landing"] }),
  component({ id: "membership-pricing", label: "Membership pricing", role: "offer", description: "Membership price cards.", suitableFor: ["fitness-studio"], qualityRules: ["Membership prices must not be invented."] }),
  component({ id: "services-with-prices", label: "Services with prices", role: "offer", description: "Service list with known prices or price ranges.", suitableFor: ["beauty-salon", "private-clinic", "fitness-studio"], requiredData: ["services"], optionalData: ["prices", "duration", "bookingUrl"], variants: ["table", "cards", "compact-list", "category-tabs"], implementationStatus: "schema-ready", qualityRules: ["Prices must only be shown when known.", "Duration must only be shown when known.", "If prices are missing, use a services grid instead."] }),
  component({ id: "treatment-detail-cards", label: "Treatment detail cards", role: "offer", description: "Treatment cards for beauty or clinic services.", suitableFor: ["beauty-salon", "private-clinic"] }),
  component({ id: "services-medical-list", label: "Medical services list", role: "offer", description: "Medical or clinical services list.", suitableFor: ["private-clinic"], qualityRules: ["Do not invent medical claims or treatment availability."] }),
  component({ id: "menu-preview", label: "Menu preview", role: "offer", description: "Preview of menu categories or signature items.", suitableFor: ["cafe-bistro", "restaurant"], requiredData: ["menuItemsOrCategories"], optionalData: ["prices", "dietaryTags", "menuPdfUrl"], variants: ["cards", "simple-list", "category-tabs", "signature-items"], implementationStatus: "schema-ready", qualityRules: ["Menu items and prices must not be invented.", "When exact menu is unknown, show general categories only.", "Menu should appear before long storytelling sections."] }),
  component({ id: "menu-tabs", label: "Menu tabs", role: "offer", description: "Tabbed food or drink menu.", suitableFor: ["restaurant", "cafe-bistro"], qualityRules: ["Do not invent menu items or prices."] }),
  component({ id: "daily-menu", label: "Daily menu", role: "offer", description: "Daily menu section when source data exists.", suitableFor: ["restaurant"], qualityRules: ["Daily menu must be sourced and dated."] }),
  component({ id: "signature-items", label: "Signature items", role: "offer", description: "Signature products or dishes.", suitableFor: ["cafe-bistro", "restaurant"], qualityRules: ["Signature items must be sourced or framed as categories."] }),
  component({ id: "product-categories", label: "Product categories", role: "commerce", description: "Product category overview.", suitableFor: ["local-retail", "micro-ecommerce"] }),
  component({ id: "featured-products", label: "Featured products", role: "commerce", description: "Featured product or assortment cards.", suitableFor: ["local-retail", "micro-ecommerce"] }),
  component({ id: "product-grid", label: "Product grid", role: "commerce", description: "Product grid for commerce or catalog pages.", suitableFor: ["micro-ecommerce", "local-retail"] }),
  component({ id: "product-detail", label: "Product detail", role: "commerce", description: "Product detail content block.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "room-cards", label: "Room cards", role: "offer", description: "Accommodation room, apartment or unit cards.", suitableFor: ["accommodation"] }),
  component({ id: "class-schedule", label: "Class schedule", role: "event", description: "Fitness or studio class schedule.", suitableFor: ["fitness-studio"], qualityRules: ["Schedule must not be invented."] }),
  component({ id: "class-cards", label: "Class cards", role: "offer", description: "Fitness or studio class cards.", suitableFor: ["fitness-studio"] }),
  component({ id: "course-outcomes", label: "Course outcomes", role: "offer", description: "Concrete course outcomes.", suitableFor: ["course-workshop"] }),
  component({ id: "course-cards", label: "Course cards", role: "offer", description: "Course cards for education websites.", suitableFor: ["course-workshop"] }),
  component({ id: "curriculum", label: "Curriculum", role: "offer", description: "Course curriculum or syllabus section.", suitableFor: ["course-workshop"] }),
  component({ id: "open-positions", label: "Open positions", role: "offer", description: "Hiring microsite open role list.", suitableFor: ["hiring-microsite"], qualityRules: ["Open positions must be sourced."] }),
  component({ id: "unit-overview", label: "Unit overview", role: "real-estate", description: "Real estate project unit overview.", suitableFor: ["real-estate-project"], qualityRules: ["Unit availability must not be invented."] }),
  component({ id: "floor-plans", label: "Floor plans", role: "real-estate", description: "Floor plan media and information.", suitableFor: ["real-estate-project"], qualityRules: ["Floor plans must be sourced assets."] }),
  component({ id: "property-highlights", label: "Property highlights", role: "real-estate", description: "Property highlight cards.", suitableFor: ["real-estate-agent", "real-estate-project"] }),
  component({ id: "property-card", label: "Property card", role: "real-estate", description: "Single property card." }),
  component({ id: "selected-works", label: "Selected works", role: "media", description: "Selected portfolio works.", suitableFor: ["creative-portfolio"] }),
  component({ id: "project-case-study", label: "Project case study", role: "story", description: "Portfolio or B2B case study block.", suitableFor: ["creative-portfolio", "consultant-expert"] }),
  component({ id: "services-packages", label: "Service packages", role: "offer", description: "Packaged expert or service offers.", suitableFor: ["consultant-expert"] }),
  component({ id: "services-mini", label: "Mini services", role: "offer", description: "Compact services section for portfolio pages.", suitableFor: ["creative-portfolio"] }),
  component({ id: "programs", label: "Programs", role: "offer", description: "Nonprofit or community program cards.", suitableFor: ["nonprofit-community"] }),
  component({ id: "benefits", label: "Benefits", role: "offer", description: "Benefit cards for hiring or offer pages.", suitableFor: ["hiring-microsite", "fitness-studio", "startup-mvp-landing"] }),

  component({ id: "primary-cta", label: "Primary CTA", role: "conversion", description: "Primary conversion action." }),
  component({ id: "secondary-cta", label: "Secondary CTA", role: "conversion", description: "Secondary conversion action." }),
  component({ id: "cta-section", label: "CTA section", role: "conversion", description: "Generic call-to-action section.", implementationStatus: "renderable" }),
  component({ id: "sticky-call-button", label: "Sticky call button", role: "conversion", description: "Sticky phone CTA for local services.", suitableFor: ["local-service"], qualityRules: ["Phone number must be sourced."] }),
  component({ id: "booking-cta", label: "Booking CTA", role: "conversion", description: "CTA section for booking a service, visit or consultation.", suitableFor: ["beauty-salon", "fitness-studio", "therapist-coach", "private-clinic", "accommodation"], requiredData: ["bookingIntent"], optionalData: ["bookingUrl", "phone", "email", "calendarUrl"], variants: ["centered", "split", "sticky-card", "minimal"], implementationStatus: "schema-ready", qualityRules: ["Booking URL must only be used when known.", "Fallback to phone or contact form when direct booking is unavailable."] }),
  component({ id: "reservation-cta", label: "Reservation CTA", role: "conversion", description: "Reservation-focused CTA.", suitableFor: ["restaurant", "cafe-bistro"], qualityRules: ["Reservation URL must be sourced."] }),
  component({ id: "visit-us-cta", label: "Visit us CTA", role: "conversion", description: "CTA encouraging a local visit.", suitableFor: ["cafe-bistro", "restaurant", "local-retail"] }),
  component({ id: "quote-request-cta", label: "Quote request CTA", role: "conversion", description: "CTA for requesting a quote.", suitableFor: ["local-service", "tradesman-craft"] }),
  component({ id: "valuation-cta", label: "Property valuation CTA", role: "conversion", description: "CTA for property valuation leads.", suitableFor: ["real-estate-agent"] }),
  component({ id: "trial-lesson-cta", label: "Trial lesson CTA", role: "conversion", description: "CTA for trial lessons or first visits.", suitableFor: ["fitness-studio"] }),
  component({ id: "registration-cta", label: "Registration CTA", role: "conversion", description: "Registration CTA for courses and workshops.", suitableFor: ["course-workshop"] }),
  component({ id: "tickets-cta", label: "Tickets CTA", role: "conversion", description: "Ticket purchase CTA.", suitableFor: ["event-microsite"], qualityRules: ["Ticket links and availability must be sourced."] }),
  component({ id: "waitlist-form", label: "Waitlist form", role: "conversion", description: "Waitlist form for MVP and startup landing pages.", suitableFor: ["startup-mvp-landing"] }),
  component({ id: "lead-magnet", label: "Lead magnet", role: "conversion", description: "Lead capture resource or offer.", suitableFor: ["consultant-expert", "real-estate-agent"] }),
  component({ id: "download-brochure", label: "Download brochure", role: "conversion", description: "Brochure download CTA.", suitableFor: ["real-estate-project"] }),
  component({ id: "application-form", label: "Application form", role: "conversion", description: "Hiring application form.", suitableFor: ["hiring-microsite"] }),
  component({ id: "lead-form", label: "Lead form", role: "conversion", description: "Project or sales lead form.", suitableFor: ["real-estate-project"] }),
  component({ id: "contact-form", label: "Contact form", role: "conversion", description: "Lead capture or inquiry form.", suitableFor: ["local-service", "tradesman-craft", "therapist-coach", "real-estate-agent", "consultant-expert", "creative-portfolio"], requiredData: ["formPurpose"], optionalData: ["fields", "privacyNote", "submitLabel"], variants: ["simple", "with-contact-card", "multi-field", "quote-request"], implementationStatus: "schema-ready", qualityRules: ["Form must have a clear purpose.", "Sensitive data fields should be avoided unless necessary.", "Privacy note should be present when collecting personal data."] }),
  component({ id: "newsletter-signup", label: "Newsletter signup", role: "conversion", description: "Newsletter signup section." }),
  component({ id: "newsletter", label: "Newsletter", role: "conversion", description: "Newsletter signup or update block.", suitableFor: ["micro-ecommerce", "event-microsite", "startup-mvp-landing"] }),
  component({ id: "calendar-booking", label: "Calendar booking", role: "conversion", description: "Calendar booking embed or link.", suitableFor: ["consultant-expert", "therapist-coach"] }),
  component({ id: "checkout-link", label: "Checkout link", role: "commerce", description: "External or internal checkout link.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "donate-cta", label: "Donate CTA", role: "conversion", description: "Donation CTA for nonprofit pages.", suitableFor: ["nonprofit-community"] }),
  component({ id: "volunteer-cta", label: "Volunteer CTA", role: "conversion", description: "Volunteer CTA for nonprofit pages.", suitableFor: ["nonprofit-community"] }),
  component({ id: "custom-order-cta", label: "Custom order CTA", role: "conversion", description: "Custom order CTA for artisan businesses.", suitableFor: ["tradesman-craft"] }),
  component({ id: "contact-cta", label: "Contact CTA", role: "conversion", description: "Minimal contact CTA for portfolio and personal pages.", suitableFor: ["creative-portfolio"] }),

  component({ id: "reviews", label: "Reviews", role: "trust", description: "Customer review section.", suitableFor: ["local-service", "cafe-bistro", "restaurant", "beauty-salon", "fitness-studio", "private-clinic", "accommodation", "local-retail", "micro-ecommerce"], requiredData: ["reviews"], optionalData: ["rating", "reviewSource", "reviewUrl"], variants: ["cards", "carousel", "rating-summary", "quotes"], implementationStatus: "schema-ready", qualityRules: ["Reviews must be sourced or omitted.", "Do not generate fake reviews.", "Rating summary must match source data."] }),
  component({ id: "review-cards", label: "Review cards", role: "trust", description: "Individual review card layout." }),
  component({ id: "google-rating-summary", label: "Google rating summary", role: "trust", description: "Google-style rating summary when source data exists.", qualityRules: ["Rating summary must match source data."] }),
  component({ id: "testimonials", label: "Testimonials", role: "trust", description: "Testimonials or client quotes.", suitableFor: ["tradesman-craft", "consultant-expert", "real-estate-agent", "course-workshop", "creative-portfolio"] }),
  component({ id: "client-logos", label: "Client logos", role: "trust", description: "Client or partner logos.", suitableFor: ["consultant-expert"], qualityRules: ["Client logos must not be invented."] }),
  component({ id: "trust-badges", label: "Trust badges", role: "trust", description: "Trust badge row." }),
  component({ id: "certifications", label: "Certifications", role: "trust", description: "Certification cards.", qualityRules: ["Certifications must be sourced."] }),
  component({ id: "credentials", label: "Credentials", role: "trust", description: "Credentials and qualifications.", suitableFor: ["therapist-coach", "private-clinic"], qualityRules: ["Credentials must be sourced."] }),
  component({ id: "awards", label: "Awards", role: "trust", description: "Awards section.", qualityRules: ["Awards must be sourced."] }),
  component({ id: "awards-press", label: "Awards and press", role: "trust", description: "Awards and press mentions for portfolio pages.", suitableFor: ["creative-portfolio"] }),
  component({ id: "press-mentions", label: "Press mentions", role: "trust", description: "Press mention logos or links." }),
  component({ id: "stats-strip", label: "Stats strip", role: "trust", description: "Compact metric row.", suitableFor: ["real-estate-agent", "consultant-expert", "nonprofit-community"], qualityRules: ["Stats must be sourced or omitted."] }),
  component({ id: "impact-stats", label: "Impact stats", role: "trust", description: "Impact metrics for nonprofit or community pages.", suitableFor: ["nonprofit-community"], qualityRules: ["Impact numbers must not be invented."] }),
  component({ id: "sold-properties", label: "Sold properties", role: "real-estate", description: "Sold property proof section.", suitableFor: ["real-estate-agent"], qualityRules: ["Sold properties must not be invented."] }),
  component({ id: "case-studies", label: "Case studies", role: "trust", description: "B2B or project case studies.", suitableFor: ["consultant-expert"], qualityRules: ["Case studies must be sourced."] }),
  component({ id: "before-after-gallery", label: "Before / after gallery", role: "media", description: "Before/after gallery for transformations, renovations and beauty services.", suitableFor: ["local-service", "beauty-salon", "tradesman-craft"], requiredData: ["beforeAfterImages"], optionalData: ["captions", "projectLabels"], variants: ["slider", "paired-grid", "case-cards"], implementationStatus: "schema-ready", qualityRules: ["Before/after media must be real and paired.", "Do not use before/after layout for unrelated images."] }),
  component({ id: "team-profiles", label: "Team profiles", role: "trust", description: "Team member profile cards.", suitableFor: ["beauty-salon", "hiring-microsite", "nonprofit-community"] }),
  component({ id: "team", label: "Team", role: "trust", description: "Team overview section.", suitableFor: ["nonprofit-community", "hiring-microsite"] }),
  component({ id: "doctor-profiles", label: "Doctor profiles", role: "trust", description: "Doctor or clinician profile cards.", suitableFor: ["private-clinic"], qualityRules: ["Names, roles and credentials must be sourced."] }),
  component({ id: "trainer-profiles", label: "Trainer profiles", role: "trust", description: "Trainer profile cards.", suitableFor: ["fitness-studio"], qualityRules: ["Certifications must not be invented."] }),
  component({ id: "instructor-profile", label: "Instructor profile", role: "trust", description: "Course instructor profile.", suitableFor: ["course-workshop"], qualityRules: ["Instructor credentials must be sourced."] }),
  component({ id: "agent-profile", label: "Agent profile", role: "trust", description: "Real estate agent profile.", suitableFor: ["real-estate-agent"] }),
  component({ id: "expert-bio", label: "Expert bio", role: "trust", description: "Consultant or expert biography.", suitableFor: ["consultant-expert"] }),
  component({ id: "employee-quotes", label: "Employee quotes", role: "trust", description: "Employee quotes for hiring pages.", suitableFor: ["hiring-microsite"], qualityRules: ["Employee quotes must be sourced."] }),
  component({ id: "partners", label: "Partners", role: "trust", description: "Partner logo or list section.", suitableFor: ["nonprofit-community"] }),
  component({ id: "sponsors", label: "Sponsors", role: "trust", description: "Sponsor logo section.", suitableFor: ["event-microsite"] }),

  component({ id: "about-section", label: "About section", role: "story", description: "Generic about section." }),
  component({ id: "about-business", label: "About business", role: "story", description: "About section for businesses.", suitableFor: ["tradesman-craft", "cafe-bistro", "restaurant", "local-retail"] }),
  component({ id: "about-expert", label: "About expert", role: "story", description: "About section for experts and advisors.", suitableFor: ["therapist-coach", "consultant-expert"] }),
  component({ id: "about-creator", label: "About creator", role: "story", description: "About section for creative portfolios.", suitableFor: ["creative-portfolio"] }),
  component({ id: "founder-note", label: "Founder note", role: "story", description: "Short founder note for MVP or startup pages.", suitableFor: ["startup-mvp-landing"] }),
  component({ id: "story-intro", label: "Story intro", role: "story", description: "Narrative opening section." }),
  component({ id: "mission-statement", label: "Mission statement", role: "story", description: "Mission statement for nonprofit and community websites.", suitableFor: ["nonprofit-community"] }),
  component({ id: "problem-solution", label: "Problem / solution", role: "story", description: "Problem and solution framing.", suitableFor: ["consultant-expert", "startup-mvp-landing"] }),
  component({ id: "problem-statement", label: "Problem statement", role: "story", description: "Focused problem statement for MVP landing pages.", suitableFor: ["startup-mvp-landing"] }),
  component({ id: "approach-section", label: "Approach section", role: "story", description: "Method or approach section.", suitableFor: ["therapist-coach", "consultant-expert"] }),
  component({ id: "craft-process", label: "Craft process", role: "story", description: "Process section for artisan work.", suitableFor: ["tradesman-craft"] }),
  component({ id: "how-it-works", label: "How it works", role: "story", description: "How-it-works steps.", suitableFor: ["startup-mvp-landing", "consultant-expert"] }),
  component({ id: "process-steps", label: "Process steps", role: "story", description: "Step-by-step process section.", suitableFor: ["local-service", "real-estate-agent", "consultant-expert"] }),
  component({ id: "timeline", label: "Timeline", role: "story", description: "Timeline section for projects or history." }),
  component({ id: "hiring-process", label: "Hiring process", role: "story", description: "Hiring process steps.", suitableFor: ["hiring-microsite"] }),
  component({ id: "company-culture", label: "Company culture", role: "story", description: "Company culture section for hiring pages.", suitableFor: ["hiring-microsite"] }),
  component({ id: "for-who-section", label: "For who section", role: "story", description: "Audience fit section.", suitableFor: ["course-workshop", "therapist-coach"] }),
  component({ id: "who-is-it-for", label: "Who is it for", role: "story", description: "Fit section for therapy, coaching or advisory services.", suitableFor: ["therapist-coach"] }),
  component({ id: "session-format", label: "Session format", role: "story", description: "Session format and what to expect.", suitableFor: ["therapist-coach"] }),
  component({ id: "use-cases", label: "Use cases", role: "story", description: "Use case cards.", suitableFor: ["startup-mvp-landing", "consultant-expert"] }),
  component({ id: "benefits-grid", label: "Benefits grid", role: "story", description: "Benefit card grid.", suitableFor: ["fitness-studio", "startup-mvp-landing", "hiring-microsite"], implementationStatus: "schema-ready" }),
  component({ id: "feature-list", label: "Feature list", role: "story", description: "Feature list section.", implementationStatus: "renderable" }),
  component({ id: "materials-section", label: "Materials section", role: "story", description: "Materials section for craft and product pages.", suitableFor: ["tradesman-craft", "micro-ecommerce"] }),
  component({ id: "amenities-grid", label: "Amenities grid", role: "story", description: "Amenities grid for accommodation or property pages.", suitableFor: ["accommodation", "real-estate-project"] }),
  component({ id: "amenities", label: "Amenities", role: "story", description: "Amenity list or cards.", suitableFor: ["real-estate-project", "accommodation"] }),
  component({ id: "location-benefits", label: "Location benefits", role: "local", description: "Location benefit section.", suitableFor: ["real-estate-project", "accommodation"] }),
  component({ id: "nearby-attractions", label: "Nearby attractions", role: "local", description: "Nearby attractions for accommodation and tourism websites.", suitableFor: ["accommodation"] }),
  component({ id: "house-rules", label: "House rules", role: "support", description: "Accommodation house rules.", suitableFor: ["accommodation"], qualityRules: ["House rules must be sourced or omitted."] }),
  component({ id: "preparation-instructions", label: "Preparation instructions", role: "support", description: "Pre-visit instructions for clinics and services.", suitableFor: ["private-clinic"] }),
  component({ id: "insurance-payment-info", label: "Insurance and payment info", role: "support", description: "Insurance and payment information.", suitableFor: ["private-clinic"], qualityRules: ["Insurance coverage and payment terms must be sourced."] }),
  component({ id: "shipping-and-returns", label: "Shipping and returns", role: "commerce", description: "Shipping and returns policy section.", suitableFor: ["micro-ecommerce"], qualityRules: ["Shipping and return policies must be sourced."] }),
  component({ id: "guarantee-or-certificate", label: "Guarantee or certificate", role: "trust", description: "Guarantee or certificate section.", qualityRules: ["Guarantees and certificates must be sourced."] }),
  component({ id: "certificate", label: "Certificate", role: "trust", description: "Course or training certificate section.", suitableFor: ["course-workshop"], qualityRules: ["Certificates must be sourced."] }),
  component({ id: "chef-story", label: "Chef story", role: "story", description: "Chef or restaurant story section.", suitableFor: ["restaurant"], qualityRules: ["Chef names and biography must be sourced."] }),
  component({ id: "private-events", label: "Private events", role: "offer", description: "Private event offer for restaurants and venues.", suitableFor: ["restaurant", "event-microsite"] }),
  component({ id: "store-benefits", label: "Store benefits", role: "story", description: "Local retail store benefits.", suitableFor: ["local-retail"] }),
  component({ id: "thought-leadership", label: "Thought leadership", role: "story", description: "Articles, insights or authority content teaser.", suitableFor: ["consultant-expert"] }),

  component({ id: "gallery", label: "Gallery", role: "media", description: "Generic image gallery.", suitableFor: ["tradesman-craft", "cafe-bistro", "restaurant", "beauty-salon", "fitness-studio", "accommodation", "creative-portfolio", "nonprofit-community"], requiredData: ["images"], optionalData: ["captions", "imageAltTexts"], variants: ["masonry", "editorial-large", "carousel", "grid-compact"], implementationStatus: "schema-ready", qualityRules: ["Images must exist in allowed uploads or approved remote assets.", "Alt text should describe the image content.", "Do not use gallery without images."] }),
  component({ id: "image-gallery", label: "Image gallery", role: "media", description: "Image gallery component." }),
  component({ id: "masonry-gallery", label: "Masonry gallery", role: "media", description: "Masonry-style image gallery." }),
  component({ id: "atmosphere-gallery", label: "Atmosphere gallery", role: "media", description: "Atmosphere-focused gallery for gastro and local businesses.", suitableFor: ["cafe-bistro", "restaurant"], qualityRules: ["Use only existing atmosphere or product images."] }),
  component({ id: "interior-gallery", label: "Interior gallery", role: "media", description: "Interior-focused gallery.", suitableFor: ["restaurant", "cafe-bistro", "accommodation"] }),
  component({ id: "portfolio-gallery", label: "Portfolio gallery", role: "media", description: "Portfolio gallery for craft and creative work.", suitableFor: ["tradesman-craft", "creative-portfolio"] }),
  component({ id: "project-gallery", label: "Project gallery", role: "media", description: "Project-focused image gallery.", suitableFor: ["real-estate-project", "tradesman-craft"] }),
  component({ id: "video-embed", label: "Video embed", role: "media", description: "Video embed block." }),
  component({ id: "product-image-grid", label: "Product image grid", role: "media", description: "Product image grid for commerce websites.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "instagram-feed", label: "Instagram feed", role: "media", description: "Instagram feed or social preview.", suitableFor: ["cafe-bistro", "restaurant", "beauty-salon", "tradesman-craft", "micro-ecommerce"] }),
  component({ id: "social-links", label: "Social links", role: "media", description: "Social link list.", suitableFor: ["creative-portfolio", "cafe-bistro", "beauty-salon", "local-retail"] }),
  component({ id: "logo-cloud", label: "Logo cloud", role: "trust", description: "Logo cloud for clients or partners." }),
  component({ id: "map-image-preview", label: "Map image preview", role: "local", description: "Static map image preview." }),
  component({ id: "team-gallery", label: "Team gallery", role: "media", description: "Team photo gallery.", suitableFor: ["hiring-microsite"] }),
  component({ id: "gallery-previous-year", label: "Previous year gallery", role: "media", description: "Gallery from previous event editions.", suitableFor: ["event-microsite"], qualityRules: ["Previous-year media must be real and dated."] }),
  component({ id: "product-preview", label: "Product preview", role: "media", description: "Product screenshot or preview section.", suitableFor: ["startup-mvp-landing"], qualityRules: ["Do not imply finished functionality unless available."] }),

  component({ id: "opening-hours", label: "Opening hours", role: "local", description: "Displays opening hours and optional notes.", suitableFor: ["cafe-bistro", "restaurant", "beauty-salon", "fitness-studio", "private-clinic", "accommodation", "local-retail"], requiredData: ["openingHours"], optionalData: ["holidayHours", "openingNote", "timezone"], variants: ["compact", "table", "cards", "with-status"], implementationStatus: "schema-ready", qualityRules: ["Do not invent opening hours.", "If opening hours are unavailable, omit this component or use contact fallback.", "For local businesses, opening hours should be visible before the footer."] }),
  component({ id: "opening-status", label: "Opening status", role: "local", description: "Opening status based on available opening hours." }),
  component({ id: "location-map", label: "Location map", role: "local", description: "Map and address section for local businesses.", suitableFor: ["local-service", "cafe-bistro", "restaurant", "beauty-salon", "fitness-studio", "private-clinic", "accommodation", "local-retail", "event-microsite"], requiredData: ["business.address"], optionalData: ["parkingInfo", "publicTransportInfo", "mapEmbedUrl", "coordinates"], variants: ["map-right", "map-full", "address-card", "compact"], implementationStatus: "schema-ready", qualityRules: ["Address must be sourced.", "Map embed should only be used when allowed and available.", "Parking and transport notes must not be invented."] }),
  component({ id: "address-block", label: "Address block", role: "local", description: "Address and contact detail block." }),
  component({ id: "parking-info", label: "Parking info", role: "local", description: "Parking information block.", qualityRules: ["Parking information must be sourced."] }),
  component({ id: "public-transport-info", label: "Public transport info", role: "local", description: "Public transport information block.", qualityRules: ["Transport information must be sourced."] }),
  component({ id: "delivery-links", label: "Delivery links", role: "local", description: "Delivery platform links for restaurants and retail.", suitableFor: ["restaurant", "cafe-bistro", "local-retail"], qualityRules: ["Delivery links must be sourced."] }),
  component({ id: "local-seo-text-block", label: "Local SEO text block", role: "seo", description: "Structured local SEO copy block." }),
  component({ id: "google-maps-embed", label: "Google Maps embed", role: "local", description: "Google Maps embed wrapper." }),
  component({ id: "venue-map", label: "Venue map", role: "event", description: "Venue map for events.", suitableFor: ["event-microsite"] }),
  component({ id: "map", label: "Map", role: "local", description: "Generic map component.", suitableFor: ["real-estate-project", "event-microsite", "local-retail", "accommodation"] }),

  component({ id: "schedule", label: "Schedule", role: "event", description: "Generic schedule section.", suitableFor: ["course-workshop", "fitness-studio", "event-microsite"] }),
  component({ id: "program-schedule", label: "Program schedule", role: "event", description: "Program schedule for events.", suitableFor: ["event-microsite"] }),
  component({ id: "events-list", label: "Events list", role: "event", description: "Event list section.", suitableFor: ["nonprofit-community", "cafe-bistro"] }),
  component({ id: "events-mini-list", label: "Events mini list", role: "event", description: "Compact event list for local businesses.", suitableFor: ["cafe-bistro", "restaurant"] }),
  component({ id: "event-card", label: "Event card", role: "event", description: "Single event card." }),
  component({ id: "speakers-or-performers", label: "Speakers or performers", role: "event", description: "Speakers, performers or guests section.", suitableFor: ["event-microsite"] }),
  component({ id: "countdown", label: "Countdown", role: "event", description: "Countdown timer for events or launches.", suitableFor: ["event-microsite", "startup-mvp-landing"] }),
  component({ id: "seasonal-pricing", label: "Seasonal pricing", role: "offer", description: "Seasonal pricing for accommodation or events.", suitableFor: ["accommodation"] }),
  component({ id: "availability-preview", label: "Availability preview", role: "conversion", description: "Availability preview for booking-oriented websites.", suitableFor: ["accommodation"] }),
  component({ id: "pricing-seasonal", label: "Seasonal pricing", role: "offer", description: "Seasonal pricing section.", suitableFor: ["accommodation"] }),

  component({ id: "category-navigation", label: "Category navigation", role: "commerce", description: "Product category navigation.", suitableFor: ["micro-ecommerce", "local-retail"] }),
  component({ id: "cart-summary", label: "Cart summary", role: "commerce", description: "Cart summary component.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "payment-methods", label: "Payment methods", role: "commerce", description: "Payment methods section.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "shipping-info", label: "Shipping info", role: "commerce", description: "Shipping information section.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "returns-info", label: "Returns info", role: "commerce", description: "Returns information section.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "special-offers", label: "Special offers", role: "commerce", description: "Special offers section.", suitableFor: ["local-retail", "micro-ecommerce"], qualityRules: ["Do not invent offers or discounts."] }),
  component({ id: "brands-carousel", label: "Brands carousel", role: "commerce", description: "Brand carousel for retail websites.", suitableFor: ["local-retail"] }),
  component({ id: "stock-status", label: "Stock status", role: "commerce", description: "Stock status indicator.", suitableFor: ["micro-ecommerce"], qualityRules: ["Stock status must be sourced from commerce data."] }),
  component({ id: "variant-selector", label: "Variant selector", role: "commerce", description: "Product variant selector.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "cross-sell-products", label: "Cross-sell products", role: "commerce", description: "Cross-sell product section.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "newsletter-commerce", label: "Commerce newsletter", role: "commerce", description: "Commerce-oriented newsletter signup.", suitableFor: ["micro-ecommerce"] }),
  component({ id: "benefits-strip", label: "Benefits strip", role: "commerce", description: "Compact product or service benefits strip.", suitableFor: ["micro-ecommerce", "startup-mvp-landing"] }),

  component({ id: "market-area", label: "Market area", role: "real-estate", description: "Market area section for agents.", suitableFor: ["real-estate-agent"] }),
  component({ id: "financing-info", label: "Financing info", role: "real-estate", description: "Financing information for real estate projects.", suitableFor: ["real-estate-project"], qualityRules: ["Financing terms must be sourced."] }),
  component({ id: "project-timeline", label: "Project timeline", role: "real-estate", description: "Real estate project timeline.", suitableFor: ["real-estate-project"] }),

  component({ id: "faq", label: "FAQ", role: "support", description: "Frequently asked questions section.", suitableFor: ["local-service", "restaurant", "beauty-salon", "fitness-studio", "therapist-coach", "private-clinic", "accommodation", "micro-ecommerce", "course-workshop", "event-microsite", "startup-mvp-landing"], requiredData: ["questions"], optionalData: ["groupLabels"], variants: ["accordion", "grouped", "two-column", "compact"], implementationStatus: "schema-ready", qualityRules: ["FAQ should answer real objections for the archetype.", "Do not invent policies, prices, availability or guarantees."] }),
  component({ id: "faq-grouped", label: "Grouped FAQ", role: "support", description: "Grouped FAQ layout." }),
  component({ id: "contact-faq", label: "Contact FAQ", role: "support", description: "FAQ focused on contact and booking questions." }),
  component({ id: "service-faq", label: "Service FAQ", role: "support", description: "FAQ for service businesses." }),
  component({ id: "booking-faq", label: "Booking FAQ", role: "support", description: "FAQ about booking and reservations." }),
  component({ id: "pricing-faq", label: "Pricing FAQ", role: "support", description: "FAQ about pricing and packages." }),
  component({ id: "legal-note", label: "Legal note", role: "support", description: "Legal note section." }),
  component({ id: "privacy-trust-note", label: "Privacy trust note", role: "support", description: "Privacy or sensitive-service trust note.", suitableFor: ["therapist-coach", "private-clinic"] }),
  component({ id: "terms-notice", label: "Terms notice", role: "support", description: "Terms notice block." }),
  component({ id: "cookie-notice", label: "Cookie notice", role: "support", description: "Cookie notice block." }),

  component({ id: "seo-config", label: "SEO config", role: "seo", description: "SEO metadata configuration.", implementationStatus: "schema-ready" }),
  component({ id: "local-business-schema", label: "LocalBusiness schema", role: "seo", description: "Structured data for local businesses." }),
  component({ id: "restaurant-schema", label: "Restaurant schema", role: "seo", description: "Structured data for restaurants." }),
  component({ id: "product-schema", label: "Product schema", role: "seo", description: "Structured data for products." }),
  component({ id: "event-schema", label: "Event schema", role: "seo", description: "Structured data for events." }),
  component({ id: "faq-schema", label: "FAQ schema", role: "seo", description: "Structured data for FAQ content." }),
  component({ id: "breadcrumb-schema", label: "Breadcrumb schema", role: "seo", description: "Structured data for breadcrumbs." }),
  component({ id: "open-graph-image", label: "Open Graph image", role: "seo", description: "Open Graph image configuration." }),
  component({ id: "sitemap-config", label: "Sitemap config", role: "seo", description: "Sitemap configuration." }),
  component({ id: "robots-config", label: "Robots config", role: "seo", description: "Robots configuration." }),
  component({ id: "analytics-config", label: "Analytics config", role: "seo", description: "Analytics configuration." }),
  component({ id: "consent-mode", label: "Consent mode", role: "seo", description: "Consent mode configuration." }),
  component({ id: "performance-image", label: "Performance image", role: "utility", description: "Performance-aware image wrapper." }),
  component({ id: "responsive-image", label: "Responsive image", role: "utility", description: "Responsive image wrapper." }),
] satisfies ComponentDefinition[];

export const componentDefinitions = Object.fromEntries(
  componentDefinitionList.map((definition) => [definition.id, definition]),
) as Record<string, ComponentDefinition>;

export const componentDefinitionIds = componentDefinitionList.map((definition) => definition.id);
