export const websiteArchetypeIds = [
  "local-service",
  "tradesman-craft",
  "cafe-bistro",
  "restaurant",
  "beauty-salon",
  "fitness-studio",
  "therapist-coach",
  "private-clinic",
  "real-estate-agent",
  "real-estate-project",
  "accommodation",
  "local-retail",
  "micro-ecommerce",
  "consultant-expert",
  "course-workshop",
  "event-microsite",
  "creative-portfolio",
  "nonprofit-community",
  "startup-mvp-landing",
  "hiring-microsite",
] as const;

export type WebsiteArchetypeId = (typeof websiteArchetypeIds)[number];

export type WebsiteArchetypeDefinition = {
  id: WebsiteArchetypeId;
  label: string;
  description: string;
  primaryGoals: string[];
  requiredComponents: string[];
  optionalComponents: string[];
  recommendedThemes: string[];
  qualityRules: string[];
};

export const websiteArchetypes: Record<WebsiteArchetypeId, WebsiteArchetypeDefinition> = {
  "local-service": {
    id: "local-service",
    label: "Local service website",
    description: "Website for trades, repair, maintenance and other local service businesses where the main conversion is a call or quote request.",
    primaryGoals: ["get_calls", "get_quote_requests", "build_local_trust"],
    requiredComponents: ["hero-service", "services-grid", "service-area-map", "reviews", "contact-form", "sticky-call-button", "faq"],
    optionalComponents: ["before-after-gallery", "pricing-from", "process-steps", "trust-badges", "contact-strip"],
    recommendedThemes: ["minimal-clean", "bold-modern", "warm-local"],
    qualityRules: [
      "Hero must state the service and location clearly.",
      "A phone or contact CTA must be visible before the footer.",
      "Service area must be explicit for local service websites.",
      "Do not invent guarantees, emergency availability or prices unless provided by source data.",
    ],
  },
  "tradesman-craft": {
    id: "tradesman-craft",
    label: "Tradesman / craft website",
    description: "Website for custom production, artisan work and crafts where portfolio, process and material quality matter.",
    primaryGoals: ["show_work_quality", "get_custom_orders", "build_craft_trust"],
    requiredComponents: ["hero-craft", "portfolio-gallery", "craft-process", "custom-order-cta", "testimonials", "contact-form"],
    optionalComponents: ["materials-section", "featured-projects", "instagram-feed", "faq", "about-business"],
    recommendedThemes: ["artisan-editorial", "warm-local", "minimal-clean"],
    qualityRules: [
      "The page must show work examples before asking for a custom order.",
      "Materials and process should be described when available.",
      "Do not invent project references.",
    ],
  },
  "cafe-bistro": {
    id: "cafe-bistro",
    label: "Cafe / bistro / bakery website",
    description: "Local gastro website focused on visits, atmosphere, menu, opening hours and map context.",
    primaryGoals: ["get_visits", "show_menu", "show_location"],
    requiredComponents: ["hero-local-gastro", "menu-preview", "opening-hours", "atmosphere-gallery", "location-map", "reviews", "visit-us-cta"],
    optionalComponents: ["signature-items", "instagram-feed", "events-mini-list", "contact-strip", "faq"],
    recommendedThemes: ["warm-local", "artisan-editorial", "minimal-clean"],
    qualityRules: [
      "Hero must mention city or neighborhood when known.",
      "Opening hours and location must be easy to find.",
      "Menu preview must not invent exact prices unless provided.",
      "Gallery should prioritize atmosphere and product photos.",
    ],
  },
  restaurant: {
    id: "restaurant",
    label: "Restaurant website",
    description: "Website for a restaurant, bistro or bar with emphasis on reservation, menu, atmosphere and location.",
    primaryGoals: ["get_reservations", "show_menu", "get_visits"],
    requiredComponents: ["hero-restaurant", "menu-tabs", "reservation-cta", "opening-hours", "location-map", "reviews", "contact-strip"],
    optionalComponents: ["daily-menu", "chef-story", "interior-gallery", "private-events", "delivery-links", "faq"],
    recommendedThemes: ["premium-dark", "warm-local", "artisan-editorial"],
    qualityRules: [
      "Reservation CTA must be clear when reservations are available.",
      "Menu must be visible before long storytelling sections.",
      "Do not invent cuisine details, awards or chef names.",
    ],
  },
  "beauty-salon": {
    id: "beauty-salon",
    label: "Beauty salon / barber / tattoo / nails website",
    description: "Website for beauty services with emphasis on style, pricing, booking and visual trust.",
    primaryGoals: ["get_bookings", "show_services", "build_visual_trust"],
    requiredComponents: ["hero-beauty", "services-with-prices", "booking-cta", "before-after-gallery", "reviews", "opening-hours", "location-map"],
    optionalComponents: ["team-profiles", "treatment-detail-cards", "instagram-feed", "faq", "contact-strip"],
    recommendedThemes: ["soft-wellness", "premium-dark", "minimal-clean"],
    qualityRules: [
      "Booking CTA must be visible before the footer.",
      "Prices must not be invented.",
      "Before/after content must only be used when images exist.",
    ],
  },
  "fitness-studio": {
    id: "fitness-studio",
    label: "Fitness / yoga / pilates / sport studio website",
    description: "Website for a studio or trainer with schedule, classes, memberships and booking.",
    primaryGoals: ["get_trial_lessons", "sell_memberships", "show_schedule"],
    requiredComponents: ["hero-fitness", "class-schedule", "trainer-profiles", "membership-pricing", "trial-lesson-cta", "location-map"],
    optionalComponents: ["benefits-grid", "gallery", "reviews", "booking-embed", "faq"],
    recommendedThemes: ["bold-modern", "minimal-clean", "warm-local"],
    qualityRules: [
      "Schedule must not be shown as exact if unavailable.",
      "Trial lesson CTA should be present for acquisition-focused pages.",
      "Trainer profiles should not invent certifications.",
    ],
  },
  "therapist-coach": {
    id: "therapist-coach",
    label: "Therapist / coach / advisor website",
    description: "Personal trust website for consultations, therapy, mentoring or advisory services.",
    primaryGoals: ["build_personal_trust", "get_consultation_bookings", "explain_approach"],
    requiredComponents: ["hero-personal-trust", "about-expert", "approach-section", "services-cards", "booking-cta", "faq", "credentials"],
    optionalComponents: ["who-is-it-for", "session-format", "testimonials", "privacy-trust-note", "contact-form"],
    recommendedThemes: ["soft-wellness", "minimal-clean", "warm-local"],
    qualityRules: [
      "Tone must be calm, precise and non-manipulative.",
      "Do not invent credentials, methods or therapy claims.",
      "For sensitive services, avoid aggressive conversion copy.",
    ],
  },
  "private-clinic": {
    id: "private-clinic",
    label: "Private clinic / medical practice website",
    description: "Website for a health or specialist practice with services, professionals, booking and operational information.",
    primaryGoals: ["get_patient_bookings", "explain_services", "build_medical_trust"],
    requiredComponents: ["hero-clinic", "services-medical-list", "doctor-profiles", "booking-cta", "opening-hours", "location-map", "faq", "footer-legal"],
    optionalComponents: ["credentials", "insurance-payment-info", "preparation-instructions", "reviews", "contact-strip"],
    recommendedThemes: ["clinical-trust", "minimal-clean", "soft-wellness"],
    qualityRules: [
      "Do not invent medical claims, certifications or insurance coverage.",
      "Booking and contact information must be easy to find.",
      "Legal and trust notes should be available for medical websites.",
    ],
  },
  "real-estate-agent": {
    id: "real-estate-agent",
    label: "Real estate agent website",
    description: "Personal brand website for an agent or small real estate team.",
    primaryGoals: ["get_property_seller_leads", "build_agent_trust", "show_market_expertise"],
    requiredComponents: ["hero-agent", "agent-profile", "sold-properties", "valuation-cta", "process-steps", "testimonials", "contact-form"],
    optionalComponents: ["market-area", "stats-strip", "lead-magnet", "property-highlights", "faq"],
    recommendedThemes: ["luxury-realty", "premium-dark", "minimal-clean"],
    qualityRules: [
      "Sold properties must not be invented.",
      "Valuation CTA should be clear and low-friction.",
      "Market area should be explicit when known.",
    ],
  },
  "real-estate-project": {
    id: "real-estate-project",
    label: "Real estate project microsite",
    description: "Microsite for a smaller development project, property sale or unit overview.",
    primaryGoals: ["get_project_leads", "show_units", "download_brochure"],
    requiredComponents: ["project-hero", "location-benefits", "unit-overview", "floor-plans", "gallery", "lead-form", "map"],
    optionalComponents: ["amenities", "timeline", "financing-info", "download-brochure", "faq"],
    recommendedThemes: ["luxury-realty", "minimal-clean", "premium-dark"],
    qualityRules: [
      "Floor plans and unit availability must not be invented.",
      "Lead form must include a clear project inquiry context.",
      "Location benefits should be factual.",
    ],
  },
  accommodation: {
    id: "accommodation",
    label: "Accommodation / guest house / apartment website",
    description: "Website for an apartment, guest house, cottage, glamping or small hotel.",
    primaryGoals: ["get_bookings", "show_rooms", "show_location"],
    requiredComponents: ["hero-accommodation", "room-cards", "amenities-grid", "gallery", "location-map", "reviews", "booking-cta", "house-rules"],
    optionalComponents: ["nearby-attractions", "pricing-seasonal", "availability-preview", "faq", "contact-strip"],
    recommendedThemes: ["warm-local", "premium-dark", "minimal-clean"],
    qualityRules: [
      "Amenities must not be invented.",
      "Booking CTA should link to known booking flow when available.",
      "Nearby attractions should be geographically plausible and factual.",
    ],
  },
  "local-retail": {
    id: "local-retail",
    label: "Local retail / store / showroom website",
    description: "Website for a local shop, showroom or store with focus on assortment, location and visits.",
    primaryGoals: ["get_store_visits", "show_products", "show_opening_hours"],
    requiredComponents: ["hero-retail", "featured-products", "product-categories", "opening-hours", "location-map", "special-offers", "contact-strip"],
    optionalComponents: ["brands-carousel", "reviews", "instagram-feed", "store-benefits", "faq"],
    recommendedThemes: ["minimal-clean", "warm-local", "bold-modern"],
    qualityRules: [
      "Product categories should reflect known assortment.",
      "Opening hours and address must be visible.",
      "Do not invent discounts or offers.",
    ],
  },
  "micro-ecommerce": {
    id: "micro-ecommerce",
    label: "Micro e-commerce / product shop website",
    description: "Small e-commerce or catalog website for a focused product range.",
    primaryGoals: ["sell_products", "build_product_trust", "grow_newsletter"],
    requiredComponents: ["hero-product-brand", "product-grid", "product-detail", "cart-summary", "shipping-and-returns", "reviews", "faq"],
    optionalComponents: ["category-navigation", "benefits-strip", "newsletter", "instagram-feed", "cross-sell-products"],
    recommendedThemes: ["minimal-clean", "artisan-editorial", "bold-modern"],
    qualityRules: [
      "Product information and prices must be sourced.",
      "Shipping and returns must not be invented.",
      "Checkout flow should be delegated to a known commerce provider when available.",
    ],
  },
  "consultant-expert": {
    id: "consultant-expert",
    label: "Consultant / B2B expert / freelancer website",
    description: "Presentation and lead-generation website for an expert, advisor or smaller B2B service.",
    primaryGoals: ["get_qualified_leads", "show_expertise", "build_authority"],
    requiredComponents: ["hero-expert", "problem-solution", "services-packages", "case-studies", "expert-bio", "lead-magnet", "contact-form"],
    optionalComponents: ["client-logos", "thought-leadership", "testimonials", "calendar-booking", "faq"],
    recommendedThemes: ["minimal-clean", "premium-dark", "bold-modern"],
    qualityRules: [
      "Case studies and client logos must not be invented.",
      "The offer must be specific enough for qualified leads.",
      "Avoid generic expert positioning.",
    ],
  },
  "course-workshop": {
    id: "course-workshop",
    label: "Course / workshop / education website",
    description: "Website for a course, training, workshop or education program.",
    primaryGoals: ["get_registrations", "explain_outcomes", "show_schedule"],
    requiredComponents: ["hero-course", "course-outcomes", "curriculum", "instructor-profile", "schedule", "pricing-plans", "registration-cta"],
    optionalComponents: ["for-who-section", "testimonials", "certificate", "faq", "contact-strip"],
    recommendedThemes: ["bold-modern", "minimal-clean", "warm-local"],
    qualityRules: [
      "Course outcomes should be concrete.",
      "Dates and prices must not be invented.",
      "Instructor credentials must be sourced.",
    ],
  },
  "event-microsite": {
    id: "event-microsite",
    label: "Event / festival / conference microsite",
    description: "Microsite for a one-off or recurring event.",
    primaryGoals: ["sell_tickets", "show_program", "explain_venue"],
    requiredComponents: ["hero-event", "date-venue-strip", "program-schedule", "tickets-cta", "venue-map", "faq", "sponsors"],
    optionalComponents: ["speakers-or-performers", "gallery-previous-year", "countdown", "newsletter", "contact"],
    recommendedThemes: ["bold-modern", "premium-dark", "playful-community"],
    qualityRules: [
      "Date, venue, ticket availability and program must not be invented.",
      "Ticket CTA must be explicit when ticketing is available.",
      "Previous year gallery must only be used with actual media.",
    ],
  },
  "creative-portfolio": {
    id: "creative-portfolio",
    label: "Creative portfolio / personal website",
    description: "Portfolio for a photographer, designer, architect, illustrator, copywriter or artist.",
    primaryGoals: ["show_work", "get_inquiries", "build_personal_brand"],
    requiredComponents: ["hero-portfolio", "selected-works", "project-case-study", "about-creator", "services-mini", "contact-cta"],
    optionalComponents: ["awards-press", "testimonials", "gallery", "social-links", "footer"],
    recommendedThemes: ["minimal-clean", "artisan-editorial", "premium-dark"],
    qualityRules: [
      "Portfolio projects must not be invented.",
      "Visual hierarchy should prioritize work samples.",
      "Contact CTA should be minimal but visible.",
    ],
  },
  "nonprofit-community": {
    id: "nonprofit-community",
    label: "Nonprofit / community project website",
    description: "Website for a nonprofit, association, club, community or local initiative.",
    primaryGoals: ["explain_mission", "get_supporters", "collect_donations_or_volunteers"],
    requiredComponents: ["hero-mission", "mission-statement", "programs", "impact-stats", "donate-cta", "volunteer-cta", "news-list"],
    optionalComponents: ["events-list", "team", "partners", "gallery", "contact"],
    recommendedThemes: ["playful-community", "warm-local", "minimal-clean"],
    qualityRules: [
      "Impact numbers must not be invented.",
      "Donation and volunteer CTAs must be transparent.",
      "Mission statement should be concrete and non-generic.",
    ],
  },
  "startup-mvp-landing": {
    id: "startup-mvp-landing",
    label: "Startup / MVP landing page",
    description: "Landing page for product validation, waitlist or an early SaaS idea.",
    primaryGoals: ["collect_waitlist", "validate_demand", "book_demo_calls"],
    requiredComponents: ["hero-saas", "problem-statement", "product-preview", "benefits-grid", "how-it-works", "waitlist-form", "faq"],
    optionalComponents: ["use-cases", "pricing-teaser", "founder-note", "testimonials", "footer"],
    recommendedThemes: ["bold-modern", "minimal-clean", "premium-dark"],
    qualityRules: [
      "The problem statement must be specific.",
      "Product preview should not imply finished functionality unless available.",
      "CTA should match stage: waitlist, demo or early access.",
    ],
  },
  "hiring-microsite": {
    id: "hiring-microsite",
    label: "Hiring / employer microsite",
    description: "Microsite for recruiting candidates into a smaller company or local operation.",
    primaryGoals: ["get_applications", "show_culture", "explain_roles"],
    requiredComponents: ["hero-hiring", "open-positions", "company-culture", "benefits", "hiring-process", "application-form"],
    optionalComponents: ["team-gallery", "employee-quotes", "location-map", "faq", "footer"],
    recommendedThemes: ["bold-modern", "warm-local", "minimal-clean"],
    qualityRules: [
      "Open positions must be sourced.",
      "Benefits must not be invented.",
      "Application process should be clear and short.",
    ],
  },
};
